#!/usr/bin/env python3
"""Offline audit of replacing ALOHA with G1 in the existing MagSafe scene."""
import csv,hashlib,json,sys
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
ROOT=Path('/home/jbnu/aloha_g1_dataset');sys.path.insert(0,str(ROOT/'tools'));SC=ROOT/'isaaclab_magsafe_fixed_scene';OUT=ROOT/'outputs/g1_in_existing_magsafe_scene';XML=Path('/home/jbnu/mujoco_menagerie/unitree_g1/g1_with_hands.xml');FULL=ROOT/'outputs/g1_magsafe_arm_dex3_full_trajectory.npz';ARM=ROOT/'converted_runs/smolvla_20k_episode49_consensus_relative_g1/g1_episode49_consensus_relative_trajectory.npz';EVENTS={176:'left phone grasp',200:'rotation start',223:'portrait reached',326:'right accessory grasp',329:'detachment start',341:'accessory removed',380:'move to charger',530:'charger attachment',586:'left release',646:'right release'}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,indent=2)+'\n')
def main():
 import mujoco,retarget_episode49_optimized_action_to_g1 as core
 OUT.mkdir(parents=True,exist_ok=True);pose=json.load(open(SC/'magsafe_robot_preview_config.json'))['g1'];sem=json.load(open(ROOT/'outputs/task_frame_registration/magsafe_task_semantic_definition.json'));root=np.array(pose['position_xyz_m']);Rw=Rotation.from_quat(np.array(pose['orientation_wxyz'])[[1,2,3,0]]).as_matrix();phone=np.array([.525,.2556239235301329,.830744555101841]);acc=np.array([.525,.26204794497151274,.8306324233904814]);charger=np.array(sem['charger_pad_verified_from_asset']['pad_face_center_scene_m']);padn=np.array(sem['charger_pad_verified_from_asset']['pad_outward_normal_scene'])
 z=np.load(FULL);full=z['full_qpos'];arm=z['arm_qpos'];names=z['full_joint_names'].astype(str).tolist();an=z['arm_joint_names'].astype(str).tolist();ln=z['left_dex3_joint_names'].astype(str).tolist();rn=z['right_dex3_joint_names'].astype(str).tolist();m=mujoco.MjModel.from_xml_path(str(XML));d=mujoco.MjData(m);base0=m.key_qpos[mujoco.mj_name2id(m,mujoco.mjtObj.mjOBJ_KEY,'stand')][:3];lw=mujoco.mj_name2id(m,mujoco.mjtObj.mjOBJ_BODY,'left_wrist_yaw_link');rw=mujoco.mj_name2id(m,mujoco.mjtObj.mjOBJ_BODY,'right_wrist_yaw_link');lo=np.array([.0415,.003,0]);ro=np.array([.0415,-.003,0]);rows=[];all_lp=[];all_rp=[];contacts=set();placeholder=set()
 for i,q in enumerate(full):
  d.qpos[:]=q;mujoco.mj_forward(m,d);l_local=d.xpos[lw]+d.xmat[lw].reshape(3,3)@lo;r_local=d.xpos[rw]+d.xmat[rw].reshape(3,3)@ro;l=root+Rw@(l_local-base0);r=root+Rw@(r_local-base0);all_lp.append(l);all_rp.append(r)
  for j in range(d.ncon):
   c=d.contact[j];bs=[mujoco.mj_id2name(m,mujoco.mjtObj.mjOBJ_BODY,m.geom_bodyid[g]) or '' for g in (c.geom1,c.geom2)]
   if any(any(x in b for x in ('thumb','index','middle')) for b in bs):placeholder.add(i)
   elif ('torso_link' in bs and any(any(x in b for x in ('shoulder','elbow','wrist')) for b in bs)) or (any(b.startswith('left_') for b in bs) and any(b.startswith('right_') for b in bs)):contacts.add(i)
  if i in EVENTS:
   rows.append({'frame':i,'time_sec':i/30,'event':EVENTS[i],'left_palm_phone_distance_m':float(np.linalg.norm(l-phone)),'right_palm_accessory_distance_m':float(np.linalg.norm(r-acc)),'left_palm_charger_distance_m':float(np.linalg.norm(l-charger)),'inter_palm_distance_m':float(np.linalg.norm(l-r)),'left_palm_forward_x':float((Rw@d.xmat[lw].reshape(3,3)[:,0])[0]),'left_palm_forward_y':float((Rw@d.xmat[lw].reshape(3,3)[:,0])[1]),'left_palm_forward_z':float((Rw@d.xmat[lw].reshape(3,3)[:,0])[2]),'phone_back_normal_x':0.,'phone_back_normal_y':1.,'phone_back_normal_z':0.,'charger_pad_normal_x':padn[0],'charger_pad_normal_y':padn[1],'charger_pad_normal_z':padn[2]})
 with open(OUT/'event_raw_distances.csv','w',newline='') as f:w=csv.DictWriter(f,rows[0]);w.writeheader();w.writerows(rows)
 lim=np.array([m.jnt_range[mujoco.mj_name2id(m,mujoco.mjtObj.mjOBJ_JOINT,n)] for n in an]);step=np.abs(np.diff(arm,axis=0));struct={'finite':bool(np.isfinite(full).all()),'joint_limit_violations':int(np.sum((arm<lim[:,0])|(arm>lim[:,1]))),'max_joint_step_rad':float(step.max()),'max_velocity_rad_s':float((step*30).max()),'max_acceleration_rad_s2':float((np.abs(np.diff(arm,n=2,axis=0))*900).max()),'arm_cross_torso_collision_frames':len(contacts),'placeholder_dex3_contact_frames':len(placeholder),'placeholder_status':'PLACEHOLDER_HAND_DIAGNOSTIC_ONLY'};dump(OUT/'structural_metrics.json',struct)
 audit={'status':'PASS','authoritative_scene':str(SC/'generated/magsafe_magnetic_scene_v2.usda'),'scene_builder':str(SC/'magsafe_scene_builder.py'),'aloha_replay':str(SC/'replay_magsafe_aloha_episode.py'),'scene_mode_reused':'kinematic objects frozen; physical-task asset composition retained','robot_independent':['/World/MagSafeScene/Table','/World/MagSafeScene/Phone','/World/MagSafeScene/Accessory','/World/MagSafeScene/Charger','/World/MagSafeScene/MagneticJoints/AccessoryPhone','CAMERAS','lighting authored in scene'],'aloha_specific':['/World/StationaryALOHA','/World/StationaryALOHA/Asset/Geometry/tabletop_link/ReplayWorldFixedJoint','14-value ALOHA state mapping','carriage gripper mapping','ALOHA contact/grasp controllers'],'camera_poses':{'source':str(SC/'robot_model_preview_common.py'),'names':['overview','front','side','top']},'g1_prim':'/World/G1','g1_articulation':'/World/G1/Asset/root_joint','g1_usd':'/home/jbnu/robot_assets_sources/unitree_sim_isaaclab_usds/extracted/assets/robots/g1-29dof-dex3-base-fix-usd/g1_29dof_with_dex3_base_fix.usd','g1_root_pose':pose,'g1_root_pose_source':str(SC/'magsafe_robot_preview_config.json'),'g1_forward_convention':'asset +X rotated by configured +90deg about scene +Z','arm_input':str(ARM),'full_input':str(FULL),'frames':990,'fps':30,'mapping':'NAME_BASED','arm_joint_names':an,'left_dex3_joint_names':ln,'right_dex3_joint_names':rn,'missing_joint_count_previous_verified_isaac_run':0,'object_poses':{'phone':phone.tolist(),'accessory':acc.tolist(),'charger_pad_face':charger.tolist()},'hashes':{'aloha_replay':sha(SC/'replay_magsafe_aloha_episode.py'),'scene_builder':sha(SC/'magsafe_scene_builder.py'),'scene_usd':sha(SC/'generated/magsafe_magnetic_scene_v2.usda'),'arm':sha(ARM),'full':sha(FULL)}};dump(OUT/'audit/aloha_scene_replay_audit.json',audit)
 quick=json.load(open(ROOT/'outputs/quick_scene_registered_preview/global_scene_anchor.json'));debug={'classification':'FRAME_TARGET_REGISTRATION_DIFFERS_NOT_OBJECT_ASSET','existing_g1_root_pose':pose,'provisional_g1_pose_source':'same preview config used by approval renderer','existing_object_pose_source':'magsafe_magnetic_scene_v2.usda','provisional_object_geometry_source':'manually mirrored MuJoCo diagnostic geometry','provisional_global_target_translation_m':quick['translation_m'],'existing_scene_global_anchor_recomputed':False,'root_pose_difference':'NONE_BY_CONFIG','camera_difference':'quick MuJoCo free cameras vs authoritative Isaac CAMERAS','primary_difference':'quick preview shifted G1 task targets in local G1 frame; existing-scene replay applies frozen trajectory without target re-registration','left_palm_scene_event_positions':{str(fr):np.asarray(all_lp)[fr].tolist() for fr in EVENTS},'right_palm_scene_event_positions':{str(fr):np.asarray(all_rp)[fr].tolist() for fr in EVENTS}};dump(OUT/'provisional_vs_existing_scene_debug.json',debug)
 gate={'status':'G1_REPLACEMENT_REPLAY_REQUIRES_FRAME_OR_ROOT_DEBUG','reason':'Raw event distances require video review; physics grasp gate remains closed.','ready_for_physics_grasp':False,'videos_generated':False,'hardware_used':False};dump(OUT/'next_stage_gate.json',gate);print(json.dumps({'audit':audit['status'],'structural':struct,'gate':gate},indent=2))
if __name__=='__main__':main()
