#!/usr/bin/env python3
"""Offline root-cause diagnosis for the failed scene-registered G1 target."""
from __future__ import annotations
import csv,hashlib,json,sys
from pathlib import Path
import numpy as np
from scipy.spatial.transform import Rotation
ROOT=Path('/home/jbnu/aloha_g1_dataset');sys.path[:0]=[str(ROOT),str(ROOT/'tools')]
OUT=ROOT/'outputs/scene_registration_failure_diagnosis';ACTION=ROOT/'evaluation/smolvla_episode49_temporal_consensus/episode_000049_temporal_consensus.npz';FROZEN=ROOT/'converted_runs/smolvla_20k_episode49_consensus_relative_g1/g1_episode49_consensus_relative_trajectory.npz';RAW=ROOT/'raw_recordings/GoPark_20260729_111223/data/chunk-000/episode_000000.parquet';SEM=ROOT/'outputs/task_frame_registration/magsafe_task_semantic_definition.json';TIMELINE=ROOT/'configs/episode49_task_timeline.approved.json';QUICK=ROOT/'outputs/quick_scene_registered_preview';EVENTS=[176,223,326,341,530,586,646];SCALE=.42
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,indent=2)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def rot_error(a,b):return float(np.linalg.norm(Rotation.from_matrix(a.T@b).as_rotvec()))
def fk(core,model,x):q,_=core.aloha.mapped_qpos(x);return core.aloha.fk(model,q)
def source_sanity(core):
 import pandas as pd,matplotlib.pyplot as plt
 opt=np.load(ACTION)['optimized_action'].astype(float);df=pd.read_parquet(RAW);gt=np.stack(df['action']).astype(float);state=np.stack(df['observation.state']).astype(float);model,_=core.aloha.load_validated_model(core.ALOHA_XML);ko,kg,ks=fk(core,model,opt),fk(core,model,gt),fk(core,model,state)
 rows=[]
 for fr in EVENTS:
  row={'frame':fr,'joint_rmse_rad':float(np.sqrt(np.mean((opt[fr]-gt[fr])**2))),'joint_mae_rad':float(np.mean(abs(opt[fr]-gt[fr]))),'left_tcp_position_error_m':float(np.linalg.norm(ko['left_position_m'][fr]-kg['left_position_m'][fr])),'right_tcp_position_error_m':float(np.linalg.norm(ko['right_position_m'][fr]-kg['right_position_m'][fr])),'left_gripper_difference':float(opt[fr,6]-gt[fr,6]),'right_gripper_difference':float(opt[fr,13]-gt[fr,13])}
  lo=Rotation.from_quat(ko['left_quaternion_wxyz'][fr,[1,2,3,0]]).as_matrix();lg=Rotation.from_quat(kg['left_quaternion_wxyz'][fr,[1,2,3,0]]).as_matrix();ro=Rotation.from_quat(ko['right_quaternion_wxyz'][fr,[1,2,3,0]]).as_matrix();rg=Rotation.from_quat(kg['right_quaternion_wxyz'][fr,[1,2,3,0]]).as_matrix();row['left_relative_rotation_error_deg']=np.degrees(rot_error(lo,lg));row['right_relative_rotation_error_deg']=np.degrees(rot_error(ro,rg));rows.append(row)
 le=np.linalg.norm(ko['left_position_m']-kg['left_position_m'],axis=1);re=np.linalg.norm(ko['right_position_m']-kg['right_position_m'],axis=1);plausible=float(np.sqrt(np.mean(np.r_[le,re]**2)))<.03
 out={'classification':'SOURCE_VLA_ACTION_PLAUSIBLE' if plausible else 'SOURCE_VLA_ACTION_DIVERGED','criterion':'diagnostic source TCP combined RMSE < 0.03 m','action_hash':sha(ACTION),'raw_parquet_hash':sha(RAW),'shape':list(opt.shape),'overall_joint_mae_rad':float(np.mean(abs(opt-gt))),'overall_joint_rmse_rad':float(np.sqrt(np.mean((opt-gt)**2))),'left_tcp_rmse_m':float(np.sqrt(np.mean(le**2))),'right_tcp_rmse_m':float(np.sqrt(np.mean(re**2))),'events':rows,'observation_state_available':True};dump(OUT/'source_vla_vs_gt_metrics.json',out)
 fig,ax=plt.subplots(1,2,figsize=(12,5));ax[0].plot(kg['left_position_m'][:,0],kg['left_position_m'][:,2],label='GT');ax[0].plot(ko['left_position_m'][:,0],ko['left_position_m'][:,2],label='SmolVLA');ax[1].plot(kg['right_position_m'][:,0],kg['right_position_m'][:,2],label='GT');ax[1].plot(ko['right_position_m'][:,0],ko['right_position_m'][:,2],label='SmolVLA');[a.set(xlabel='X (m)',ylabel='Z (m)') for a in ax];ax[0].set_title('Left TCP');ax[1].set_title('Right TCP');ax[0].legend();fig.savefig(OUT/'source_vla_vs_gt_keyframes.png',dpi=300,bbox_inches='tight');plt.close(fig)
 return out,ko
def frame_and_anchor(core,info):
 import matplotlib.pyplot as plt,mujoco
 z=np.load(FROZEN);fq=z['g1_arm_joint_trajectory'];lp=z['g1_target_left_position'];rp=z['g1_target_right_position'];sem=json.load(open(SEM));grasp=np.array(sem['poses']['initial_phone_pose']['left_grasp_frame']['position_scene_m']);shift=grasp-lp[176];after=lp+shift
 d=mujoco.MjData(info['model']);s=core.frame_state(info,d,fq[176]);R=core.ik.quat_to_mat(s['left_quat']);offset=np.array(core.ik.LEFT_PALM_OFFSET);wrist=s['left_pos']-R@offset;palm_from_wrist=wrist+R@offset
 inv=float(np.linalg.norm(after[176]-grasp));anchor={'classification':'ANCHOR_INVARIANT_PASS' if inv<1e-6 else 'ANCHOR_COMPOSITION_BUG','frame':176,'phone_left_grasp_scene_m':grasp.tolist(),'before_left_palm_target_m':lp[176].tolist(),'global_translation_m':shift.tolist(),'after_left_palm_target_m':after[176].tolist(),'invariant_error_m':inv,'scale':SCALE,'translation_application':'p_after=p_before+translation; column-vector coordinates stored as row samples','units':'meter','object_pose_changed':False};dump(OUT/'anchor_invariant.json',anchor)
 audit={'classification':'PALM_WRIST_MAPPING_PASS' if np.linalg.norm(palm_from_wrist-s['left_pos'])<1e-10 else 'PALM_WRIST_FRAME_MISMATCH','ik_controlled_frame':'palm proxy computed by compute_palm_pose_and_jacobian','controlled_parent_body':'left_wrist_yaw_link/right_wrist_yaw_link','left_wrist_body_origin_m':wrist.tolist(),'left_palm_proxy_m':s['left_pos'].tolist(),'left_palm_reconstructed_m':palm_from_wrist.tolist(),'left_local_offset_m':offset.tolist(),'offset_rotation_applied':True,'metric_frame':'same palm proxy returned by frame_state','visualization_frame':'same rotated wrist-local palm offset','dex3_hand_base':'wrist_yaw_link child hand geometry; not used as IK point'};dump(OUT/'palm_wrist_frame_audit.json',audit)
 fig,ax=plt.subplots(figsize=(7,6));pts=np.vstack((lp[176],after[176],grasp,s['left_pos'],wrist));labs=['before target','after target','phone grasp','frozen palm','wrist origin'];ax.scatter(pts[:,0],pts[:,2]);[ax.annotate(t,(p[0],p[2])) for p,t in zip(pts,labs)];ax.set(xlabel='X (m)',ylabel='Z (m)',title='Anchor frame 176 (scene/G1 fixed world)');fig.savefig(OUT/'anchor_frame_debug.png',dpi=300,bbox_inches='tight');plt.close(fig)
 fig,ax=plt.subplots(figsize=(7,6));ax.plot([wrist[0],s['left_pos'][0]],[wrist[2],s['left_pos'][2]],'-o',label='rotated local offset');ax.scatter(grasp[0],grasp[2],label='phone grasp');ax.legend();ax.set(xlabel='X (m)',ylabel='Z (m)',title='Wrist body origin vs palm proxy');fig.savefig(OUT/'palm_wrist_frame_audit.png',dpi=300,bbox_inches='tight');plt.close(fig)
 return anchor,audit,{'lp':after,'rp':rp+shift,'fq':fq,'start':z['g1_start_arm_q'],'shift':shift}
def static_reach(core,info,tar):
 import mujoco,generate_aloha_work_posture_dex3 as work,matplotlib.pyplot as plt
 frames=[176,223,326,341,530];d=mujoco.MjData(info['model']);prev=tar['start'].copy();rows=[];best={}
 for fr in frames:
  trials=[]
  for label,seed in [('natural',tar['start']),('frozen_same_frame',tar['fq'][fr]),('previous_static',prev)]:
   s0=core.frame_state(info,d,seed);res=work.solve_frame(info,d,tar['lp'][fr],tar['rp'][fr],s0['left_quat'],s0['right_quat'],seed,seed,tar['start'],0.,200);q=res['q'];s=core.frame_state(info,d,q);le=float(np.linalg.norm(s['left_pos']-tar['lp'][fr]));re=float(np.linalg.norm(s['right_pos']-tar['rp'][fr]));margin=float(np.min(np.minimum(q-info['joint_limits'][:,0],info['joint_limits'][:,1]-q)));row={'frame':fr,'seed':label,'target_left_x':tar['lp'][fr,0],'target_left_y':tar['lp'][fr,1],'target_left_z':tar['lp'][fr,2],'target_right_x':tar['rp'][fr,0],'target_right_y':tar['rp'][fr,1],'target_right_z':tar['rp'][fr,2],'initial_left_residual_m':float(np.linalg.norm(s0['left_pos']-tar['lp'][fr])),'initial_right_residual_m':float(np.linalg.norm(s0['right_pos']-tar['rp'][fr])),'final_left_residual_m':le,'final_right_residual_m':re,'converged_5mm':le<=.005 and re<=.005,'joint_limit_violation':margin<0,'minimum_joint_margin_rad':margin,'achieved_left':s['left_pos'].tolist(),'achieved_right':s['right_pos'].tolist(),'shoulder_target_distance_note':'not used as a reachability threshold'};rows.append(row);trials.append((le+re,q,row))
  pick=min(trials,key=lambda x:x[0]);prev=pick[1];best[fr]=pick[2]
 with open(OUT/'static_reachability.csv','w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(rows[0]));w.writeheader();w.writerows(rows)
 vd=OUT/'static_reachability_views';vd.mkdir(parents=True,exist_ok=True)
 for fr in frames:
  r=best[fr]
  for view,ids in [('front',(1,2)),('side',(0,2)),('top',(0,1))]:
   fig,ax=plt.subplots(figsize=(6,5));ta=np.array([r['target_left_x'],r['target_left_y'],r['target_left_z']]);tb=np.array([r['target_right_x'],r['target_right_y'],r['target_right_z']]);aa=np.array(r['achieved_left']);ab=np.array(r['achieved_right']);ax.plot([ta[ids[0]],aa[ids[0]]],[ta[ids[1]],aa[ids[1]]],'-o',label='left');ax.plot([tb[ids[0]],ab[ids[0]]],[tb[ids[1]],ab[ids[1]]],'-o',label='right');ax.legend();ax.set_title(f'Frame {fr}: target to achieved');fig.savefig(vd/f'frame_{fr}_{view}.png',dpi=200,bbox_inches='tight');plt.close(fig)
 reachable=all(r['converged_5mm'] for r in best.values());summary={'classification':'STATIC_TARGETS_REACHABLE' if reachable else 'STATIC_SCENE_TARGET_UNREACHABLE','all_targets_reachable':reachable,'best_by_frame':best,'unreachable_frames':[f for f,r in best.items() if not r['converged_5mm']],'scene_or_robot_pose_changed':False,'status_if_unreachable':'USER_APPROVAL_REQUIRED_FOR_SCENE_PLACEMENT'};dump(OUT/'static_reachability_summary.json',summary);return summary
def geometry_fit(ko,tar):
 sem=json.load(open(SEM));phone=np.array(sem['poses']['initial_phone_pose']['left_grasp_frame']['position_scene_m']);phone_center=np.array(sem['poses']['initial_phone_pose']['position_scene_m']);acc=phone_center+np.array([0,.006425,0]);charger=np.array(sem['charger_pad_verified_from_asset']['pad_face_center_scene_m']);src=np.vstack((ko['left_position_m'][176],ko['right_position_m'][326],ko['left_position_m'][530]));dst=np.vstack((phone,acc,charger));mapped=np.vstack((tar['lp'][176],tar['rp'][326],tar['lp'][530]));current=np.linalg.norm(mapped-dst,axis=1)
 def fit(sim):
  x=src-src.mean(0);y=dst-dst.mean(0);u,s,vt=np.linalg.svd(x.T@y);R=u@vt
  if np.linalg.det(R)<0:u[:,-1]*=-1;R=u@vt
  scale=float(s.sum()/np.sum(x*x)) if sim else 1.;t=dst.mean(0)-scale*src.mean(0)@R;pred=scale*src@R+t;return {'scale':scale,'rotation':R.tolist(),'translation':t.tolist(),'residual_m':np.linalg.norm(pred-dst,axis=1).tolist(),'rmse_m':float(np.sqrt(np.mean((pred-dst)**2)))}
 rigid,similarity=fit(False),fit(True);out={'classification':'CURRENT_TRANSFORM_INCONSISTENT' if max(current)>.05 else 'SEMANTIC_GEOMETRY_COMPATIBLE','current_residual_m':current.tolist(),'current_rmse_m':float(np.sqrt(np.mean((mapped-dst)**2))),'best_fit_rigid_diagnostic_only':rigid,'best_fit_similarity_diagnostic_only':similarity,'best_fit_applied':False,'fixed_scale':SCALE,'fixed_scale_changed':False};dump(OUT/'semantic_waypoint_fit.json',out);return out
def figure(anchor,audit,static,fit):
 import matplotlib.pyplot as plt
 fig,ax=plt.subplots(2,3,figsize=(16,9));ax=ax.ravel();ax[0].axis('off');ax[0].text(0,.9,'A. Source ALOHA\nSee source_vla_vs_gt_keyframes.png',fontsize=13);a=np.array(anchor['before_left_palm_target_m']);b=np.array(anchor['after_left_palm_target_m']);g=np.array(anchor['phone_left_grasp_scene_m']);ax[1].plot([a[0],b[0]],[a[2],b[2]],'-o');ax[1].scatter(g[0],g[2],marker='x');ax[1].set_title('B. Anchor before/after');w=np.array(audit['left_wrist_body_origin_m']);p=np.array(audit['left_palm_proxy_m']);ax[2].plot([w[0],p[0]],[w[2],p[2]],'-o');ax[2].set_title('C. Wrist vs palm proxy');fr=list(static['best_by_frame']);res=[min(static['best_by_frame'][f]['final_left_residual_m'],static['best_by_frame'][f]['final_right_residual_m']) for f in fr];ax[3].bar([str(x) for x in fr],res);ax[3].set_ylabel('best residual (m)');ax[3].set_title('D. Static reachability');ax[4].bar(['current','rigid','similarity'],[fit['current_rmse_m'],fit['best_fit_rigid_diagnostic_only']['rmse_m'],fit['best_fit_similarity_diagnostic_only']['rmse_m']]);ax[4].set_title('E. Semantic waypoint fit');ax[5].axis('off');ax[5].text(0,.8,'No repaired candidate generated\nScene targets are statically unreachable\nNo scene/root/object pose changed',fontsize=13,color='red');fig.suptitle('Scene registration failure localization (diagnostic only)');(OUT/'report').mkdir(parents=True,exist_ok=True);fig.savefig(OUT/'report/figure_failure_localization.png',dpi=300,bbox_inches='tight');plt.close(fig)
def main():
 print('SIMULATION DIAGNOSIS ONLY\nNO REAL G1 OR ALOHA\nNO DDS OR PUBLISHER')
 import retarget_episode49_optimized_action_to_g1 as core
 src,ko=source_sanity(core);info=core.ik.validate_model(core.G1_XML);anchor,palm,tar=frame_and_anchor(core,info);static=static_reach(core,info,tar);dump(OUT/'temporal_window_diagnosis.json',{'classification':'NOT_RUN_STATIC_TARGETS_UNREACHABLE','rule':'Temporal windows run only after static success','quick_preview_secondary_bug':'whole-trajectory temporal_solve was initialized directly from frozen qpos instead of position_seed; this is proven but cannot repair unreachable static targets','code_change_applied':False});fit=geometry_fit(ko,tar)
 primary='SOURCE_VLA_ACTION_FAILURE' if src['classification'].endswith('DIVERGED') else ('ANCHOR_TRANSFORM_IMPLEMENTATION_BUG' if anchor['classification']!='ANCHOR_INVARIANT_PASS' else ('PALM_WRIST_FRAME_MISMATCH' if palm['classification']!='PALM_WRIST_MAPPING_PASS' else ('SCENE_TARGET_UNREACHABLE_FROM_CURRENT_G1_ROOT' if not static['all_targets_reachable'] else 'TEMPORAL_IK_INTEGRATION_BUG')))
 secondary=['QUICK_PREVIEW_TEMPORAL_SEED_INTEGRATION_BUG'];secondary+=['SOURCE_TARGET_TASK_GEOMETRY_MISMATCH'] if fit['classification']!='SEMANTIC_GEOMETRY_COMPATIBLE' else []
 root={'primary_cause':primary,'secondary_causes':secondary,'source':src['classification'],'anchor':anchor['classification'],'palm_wrist':palm['classification'],'static':static['classification'],'temporal':'NOT_RUN_STATIC_TARGETS_UNREACHABLE','semantic_geometry':fit['classification'],'scene_or_robot_pose_changed':False,'repaired_candidate_generated':False,'status':'CURRENT G1 SCENE PLACEMENT IS UNREACHABLE; NO SCENE OR ROBOT POSE WAS CHANGED; USER APPROVAL REQUIRED'};dump(OUT/'root_cause.json',root);figure(anchor,palm,static,fit);print(root['status']);return 2
if __name__=='__main__':raise SystemExit(main())
