#!/usr/bin/env python3
"""MuJoCo validation, plots, videos, tables, and dashboard for retargeting methods."""
from __future__ import annotations
import argparse,csv,hashlib,html,json,sys
from pathlib import Path
import numpy as np
ROOT=Path('/home/jbnu/aloha_g1_dataset');sys.path.insert(0,str(ROOT/'tools'));from diagnose_g1_collision_root_cause import classify,geom_ids,mindist
OUT=ROOT/'outputs/retargeting_method_comparison';XML=Path('/home/jbnu/mujoco_menagerie/unitree_g1/g1_with_hands.xml');METHODS=('relative_temporal_proposed','relative_framewise','relative_no_workspace_scale')
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,indent=2)+'\n')
def stat(x):return {'mean':float(np.mean(x)),'max':float(np.max(x,initial=0))}
def validate(method):
 import mujoco,time
 td=OUT/'trajectories'/method;z=np.load(td/'full_trajectory_placeholder_dex3.npz',allow_pickle=False);a=np.load(td/'arm_trajectory.npz',allow_pickle=True);q=z['full_qpos'];arm=z['arm_qpos'];fps=float(z['fps']);m=mujoco.MjModel.from_xml_path(str(XML));d=mujoco.MjData(m);names=z['full_joint_names'].astype(str);an=z['arm_joint_names'].astype(str);ids=[list(names).index(n) for n in an]
 limits=[]
 for n in an:j=mujoco.mj_name2id(m,mujoco.mjtObj.mjOBJ_JOINT,n);limits.append(m.jnt_range[j])
 limits=np.asarray(limits);viol=int(np.sum((arm<limits[:,0])|(arm>limits[:,1])));contacts=[];wrist_contacts=[]
 torso=geom_ids(m,lambda b,mesh,g:b=='torso_link' and m.geom_group[g]==3);palm={s:geom_ids(m,lambda b,mesh,g,s=s:b==f'{s}_wrist_yaw_link' and mesh==f'{s}_hand_palm_link' and m.geom_group[g]==3) for s in ('left','right')};wbody=[mujoco.mj_name2id(m,mujoco.mjtObj.mjOBJ_BODY,f'{s}_wrist_yaw_link') for s in ('left','right')];pclear=[[],[]];wd=[]
 t=time.perf_counter()
 for f,x in enumerate(q):
  d.qpos[:]=x;d.qvel[:]=0;mujoco.mj_forward(m,d);wd.append(np.linalg.norm(d.xpos[wbody[0]]-d.xpos[wbody[1]]));pclear[0].append(mindist(m,d,palm['left'],torso)[0]);pclear[1].append(mindist(m,d,palm['right'],torso)[0])
  for c in d.contact:
   bs=[]
   for g in (c.geom1,c.geom2):bs.append(mujoco.mj_id2name(m,mujoco.mjtObj.mjOBJ_BODY,int(m.geom_bodyid[g])) or 'world')
   cat=classify(*bs);contacts.append((f,cat,bs,-float(c.dist)))
   if not ('hand_' in bs[0] or 'hand_' in bs[1]):wrist_contacts.append((f,cat,bs,-float(c.dist)))
 runtime=time.perf_counter()-t;vel=np.diff(arm,axis=0)*fps;acc=np.diff(arm,n=2,axis=0)*fps**2;jerk=np.diff(arm,n=3,axis=0)*fps**3;err=np.c_[np.linalg.norm(a['target_left_wrist_position']-a['achieved_left_wrist_position'],axis=1),np.linalg.norm(a['target_right_wrist_position']-a['achieved_right_wrist_position'],axis=1)];steps=np.abs(np.diff(arm,axis=0));norm=np.linalg.norm(np.diff(arm,axis=0),axis=1);branch=sum(norm[i-1]>max(.15,8*max(np.median(norm[max(0,i-10):min(len(norm),i+9)]),1e-5)) for i in range(1,len(arm)))
 rv=a['solver_runtime_sec'].item();runtime_value=None if rv is None or (isinstance(rv,float) and not np.isfinite(rv)) else float(rv);metric={'method':method,'frames':len(arm),'fps':fps,'ik_success_rate':float(np.mean(a['ik_success'])),'left_wrist_rmse_m':float(np.sqrt(np.mean(err[:,0]**2))),'right_wrist_rmse_m':float(np.sqrt(np.mean(err[:,1]**2))),'wrist_max_error_m':float(err.max()),'joint_limit_violations':viol,'max_joint_step_rad':float(steps.max()),'velocity_rad_s':stat(np.abs(vel)),'acceleration_rad_s2':stat(np.abs(acc)),'jerk_rad_s3':stat(np.abs(jerk)),'branch_discontinuity_count':int(branch),'left_palm_torso_min_m':float(min(pclear[0])),'right_palm_torso_min_m':float(min(pclear[1])),'inter_wrist_min_m':float(min(wd)),'arm_level_collision_frames':len({x[0] for x in wrist_contacts}),'solver_runtime_sec':runtime_value,'mujoco_evaluation_runtime_sec':runtime,'structural_validation':'PASS' if viol==0 and np.isfinite(q).all() and np.array_equal(q[:,ids],arm) else 'FAIL'}
 md=OUT/'mujoco'/method;dump(md/'trajectory_metrics.json',metric);dump(md/'structural_validation.json',{'status':metric['structural_validation'],'arm_exactly_preserved_in_full':bool(np.array_equal(q[:,ids],arm)),'joint_limit_violations':viol,'finite':bool(np.isfinite(q).all())});dump(md/'arm_level_collision.json',{'finger_geoms_masked':True,'collision_frames':metric['arm_level_collision_frames'],'records':len(wrist_contacts),'status':'PASS' if not wrist_contacts else 'CONTACTS_PRESENT'});cats={c:sum(x[1]==c for x in contacts) for c in sorted({x[1] for x in contacts})};dump(md/'full_hand_diagnostic.json',{'warning':'PLACEHOLDER DEX3; FULL-HAND COLLISION RESULT IS DIAGNOSTIC ONLY','records':len(contacts),'frames':len({x[0] for x in contacts}),'categories':cats,'used_for_primary_ranking':False});dump(td/'validation.json',metric);return metric,a,z
def render(method,z,path,size=(640,480)):
 import mujoco,imageio.v2 as imageio
 from PIL import Image,ImageDraw
 m=mujoco.MjModel.from_xml_path(str(XML));d=mujoco.MjData(m);r=mujoco.Renderer(m,size[1],size[0]);cam=mujoco.MjvCamera();cam.type=mujoco.mjtCamera.mjCAMERA_FREE;cam.lookat[:]=[.10,0,1.0];cam.distance=1.15;cam.azimuth=90;cam.elevation=-8;path.parent.mkdir(parents=True,exist_ok=True);w=imageio.get_writer(path,fps=float(z['fps']),codec='libx264',quality=7)
 for f,q in enumerate(z['full_qpos']):d.qpos[:]=q;mujoco.mj_forward(m,d);r.update_scene(d,camera=cam);im=Image.fromarray(r.render());dr=ImageDraw.Draw(im);dr.rectangle((0,0,size[0],42),fill='black');dr.text((5,4),f'{method} frame={f} t={f/float(z["fps"]):.2f}s L={z["left_phase"][f]} R={z["right_phase"][f]}',fill='white');dr.text((5,22),'SIMULATION ONLY | PLACEHOLDER DEX3',fill='orange');w.append_data(np.asarray(im))
 w.close();r.close()
def audit():
 entries=[('ALOHA FK','tools/validate_smolvla_in_stationary_aloha_mujoco.py','mapped_qpos; fk','validated stationary ALOHA XML FK','no'),('Relative position','tools/retarget_episode49_consensus_relative_bimanual_to_g1.py','relative_targets','first-frame midpoint/vector deltas','yes'),('Axis alignment','tools/retarget_episode49_optimized_action_to_g1.py','ALIGN_RPY','[0,-7,0] deg','no'),('Workspace scale','same','SCALE','0.42','yes: 1.0'),('Initial anchor','relative converter','load_natural_start','validated natural start qpos','no'),('Framewise IK','optimized converter','position_seed / solve_frame','100 iterations, previous-frame warm start','yes'),('Temporal IK','optimized converter','temporal_solve','8 iterations sparse Gauss-Newton','yes'),('Position weight','temporal_solve','wp','3.0','no'),('Bimanual relative','temporal_solve','wr','0.80','yes but not selected'),('Velocity','temporal_solve','wv','0.018','removed in framewise'),('Acceleration','temporal_solve','wa','0.030','removed in framewise'),('Joint regularization','temporal_solve','wn','0.001','no'),('LSQR damping','temporal_solve','lsqr damp','0.002','no'),('Joint limits','validate_model','XML ranges','projection each iteration','no'),('Collision objective','temporal_solve','none','NOT_PRESENT','no'),('Orientation','relative converter','temporal_solve argument','0.0','no valid ablation')]
 x={'proposed':'relative_temporal_proposed','entries':[{'item':a,'file':b,'function':c,'actual_setting':d,'proposed_role':'active verified component' if d!='NOT_PRESENT' else 'confirmed absent','ablation':e} for a,b,c,d,e in entries],'absolute_temporal':'NOT_AVAILABLE: no validated absolute frame mapping'};dump(OUT/'implementation_audit.json',x);(OUT/'implementation_audit.md').write_text('# Implementation audit\n\n'+'\n'.join(f'- **{e["item"]}** — `{e["file"]}:{e["function"]}`; {e["actual_setting"]}; Proposed role: {e["proposed_role"]}; ablation: {e["ablation"]}' for e in x['entries'])+'\n');return x
def report(metrics,data):
 import matplotlib;matplotlib.use('Agg');import matplotlib.pyplot as plt
 rd=OUT/'report';rd.mkdir(parents=True,exist_ok=True);configs=[json.load(open(OUT/'trajectories'/m/'method_config.json')) for m in METHODS];keys=('source','frames','fps','axis_alignment_rpy_deg','initial_anchor_source','joint_limits_source','orientation_weight');full=[data[m][1] for m in METHODS];same_dex=all(np.array_equal(full[0]['left_dex3_qpos'],x['left_dex3_qpos']) and np.array_equal(full[0]['right_dex3_qpos'],x['right_dex3_qpos']) for x in full[1:]);same_names=all(np.array_equal(full[0]['arm_joint_names'],x['arm_joint_names']) and np.array_equal(full[0]['full_joint_names'],x['full_joint_names']) for x in full[1:]);fair=all(all(c[k]==configs[0][k] for c in configs) for k in keys) and configs[0]['workspace_scale']==configs[1]['workspace_scale'] and configs[2]['workspace_scale']==1.0 and same_dex and same_names;dump(OUT/'fairness_validation.json',{'status':'PASS' if fair else 'FAIL','shared_fields':keys,'same_dex3_phase_and_qpos':same_dex,'same_output_joint_order':same_names,'same_mujoco_model':str(XML),'same_isaac_controller':str(ROOT/'isaaclab_magsafe_fixed_scene/replay_g1_arm_dex3_offline.py'),'same_isaac_dt_decimation':'same script and fps; physics dt-derived substeps','intentional_differences':{'relative_framewise':'temporal residuals removed','relative_no_workspace_scale':'workspace_scale 0.42 -> 1.0'},'individual_tuning':False})
 if not fair:raise RuntimeError('fairness validation failed; paper tables refused')
 fields=['method','ik_success_rate','left_wrist_rmse_m','right_wrist_rmse_m','wrist_max_error_m','joint_limit_violations','max_joint_step_rad','velocity_rad_s.max','acceleration_rad_s2.max','jerk_rad_s3.max','arm_level_collision_frames','solver_runtime_sec']
 with (rd/'paper_table_retargeting.csv').open('w',newline='') as f:w=csv.writer(f);w.writerow(fields);[w.writerow([m['method'],m['ik_success_rate'],m['left_wrist_rmse_m'],m['right_wrist_rmse_m'],m['wrist_max_error_m'],m['joint_limit_violations'],m['max_joint_step_rad'],m['velocity_rad_s']['max'],m['acceleration_rad_s2']['max'],m['jerk_rad_s3']['max'],m['arm_level_collision_frames'],m['solver_runtime_sec']]) for m in metrics]
 with (rd/'paper_table_placeholder_hand_diagnostic.csv').open('w',newline='') as f:w=csv.writer(f);w.writerow(['method','warning','records','frames']);[w.writerow([m,'DIAGNOSTIC_ONLY',*[(lambda d:d[k])(json.load(open(OUT/'mujoco'/m/'full_hand_diagnostic.json'))) for k in ('records','frames')]]) for m in METHODS]
 isa=[]
 for m in METHODS:
  p=OUT/'isaaclab'/m/'isaaclab_g1_arm_dex3_replay_summary.json';d=json.load(open(p)) if p.exists() else {'status':'NOT_RUN','overall_rmse':None,'max_error':None,'simulation_stability':'NOT_RUN'};isa.append((m,d))
 with (rd/'paper_table_isaac_tracking.csv').open('w',newline='') as f:w=csv.writer(f);w.writerow(['method','arm_rmse_rad','max_tracking_error_rad','instability','duration_sec']);[w.writerow([m,d.get('arm_rmse',d.get('overall_rmse')),d.get('max_error'),d.get('simulation_stability'),metrics[i]['frames']/metrics[i]['fps']]) for i,(m,d) in enumerate(isa)]
 labels=METHODS;colors=['#1f77b4','#ff7f0e','#2ca02c']
 def line(name,get,y):fig,ax=plt.subplots(figsize=(9,5));[ax.plot(get(data[m][0],data[m][1]),label=m,color=colors[i],alpha=.85) for i,m in enumerate(labels)];ax.set(xlabel='frame',ylabel=y);ax.legend();fig.tight_layout();fig.savefig(rd/name,dpi=160);plt.close(fig)
 line('inter_wrist_distance.png',lambda a,z:np.linalg.norm(a['achieved_left_wrist_position']-a['achieved_right_wrist_position'],axis=1),'distance (m)');line('wrist_target_error.png',lambda a,z:np.linalg.norm(a['target_left_wrist_position']-a['achieved_left_wrist_position'],axis=1)+np.linalg.norm(a['target_right_wrist_position']-a['achieved_right_wrist_position'],axis=1),'sum wrist error (m)');line('joint_velocity_comparison.png',lambda a,z:np.max(np.abs(np.diff(a['arm_qpos'],axis=0))*float(a['fps']),axis=1),'max |velocity| (rad/s)');line('joint_acceleration_comparison.png',lambda a,z:np.max(np.abs(np.diff(a['arm_qpos'],n=2,axis=0))*float(a['fps'])**2,axis=1),'max |acceleration| (rad/s²)');line('joint_jerk_comparison.png',lambda a,z:np.max(np.abs(np.diff(a['arm_qpos'],n=3,axis=0))*float(a['fps'])**3,axis=1),'max |jerk| (rad/s³)')
 for side in ('left','right'):
  fig=plt.figure(figsize=(7,6));ax=fig.add_subplot(projection='3d');[ax.plot(a[f'achieved_{side}_wrist_position'][:,0],a[f'achieved_{side}_wrist_position'][:,1],a[f'achieved_{side}_wrist_position'][:,2],label=m) for m,(a,z) in data.items()];ax.set(xlabel='x (m)',ylabel='y (m)',zlabel='z (m)');ax.legend();fig.tight_layout();fig.savefig(rd/f'{side}_wrist_trajectory_3d.png',dpi=160);plt.close(fig)
 def bar(name,key,y):fig,ax=plt.subplots(figsize=(9,4));v=[key(x) for x in metrics];ax.bar(labels,v,color=colors);ax.set(ylabel=y);ax.tick_params(axis='x',rotation=15);fig.tight_layout();fig.savefig(rd/name,dpi=160);plt.close(fig)
 bar('IK_success_comparison.png',lambda x:x['ik_success_rate'],'success fraction');bar('solver_runtime.png',lambda x:x['solver_runtime_sec'] or 0,'runtime (s)');bar('placeholder_collision_diagnostic.png',lambda x:json.load(open(OUT/'mujoco'/x['method']/'full_hand_diagnostic.json'))['frames'],'diagnostic contact frames');bar('palm_torso_clearance.png',lambda x:min(x['left_palm_torso_min_m'],x['right_palm_torso_min_m']),'minimum clearance (m)');bar('isaac_tracking_comparison.png',lambda x:next((d.get('overall_rmse') or 0 for m,d in isa if m==x['method']),0),'RMSE (rad)')
 dump(rd/'table3_actual_g1_behavior_RESERVED.json',{'status':'EMPTY_UNTIL_REAL_DATA','comparison':'VLA-generated G1 actual vs G1 expert actual','fake_results_generated':False})
 vids=''.join(f'<li><a href="../videos/{m}.mp4">{m}</a></li>' for m in METHODS);imgs=''.join(f'<img width="47%" src="{n}">' for n in ('left_wrist_trajectory_3d.png','right_wrist_trajectory_3d.png','inter_wrist_distance.png','palm_torso_clearance.png','wrist_target_error.png','joint_velocity_comparison.png','joint_acceleration_comparison.png','joint_jerk_comparison.png','IK_success_comparison.png','solver_runtime.png','isaac_tracking_comparison.png','placeholder_collision_diagnostic.png'));(rd/'index.html').write_text(f'<html><body><h1>Retargeting method comparison</h1><h2 style="color:red">PLACEHOLDER DEX3<br>FULL-HAND COLLISION RESULT IS DIAGNOSTIC ONLY<br>REAL G1 SAFETY: NOT_PERFORMED</h2><p>Methods: Proposed frozen relative temporal; frame-wise removes temporal residuals; no-scale changes only 0.42 to 1.0. Absolute: NOT_AVAILABLE.</p><p>Fairness: {fair}</p><a href="retargeting_methods_grid.mp4">Grid video</a><ul>{vids}</ul>{imgs}<h2>Review checklist</h2><ul><li>Proposed matches frozen source</li><li>Frame-wise joint jumps</li><li>No-scale reach</li><li>No left/right swap</li><li>Wrist tracking and palm clearance</li><li>Isaac vibration/tracking</li></ul></body></html>')
def main():
 p=argparse.ArgumentParser();p.add_argument('--render',action='store_true');p.add_argument('--no-render',action='store_true');a=p.parse_args();audit();metrics=[];data={}
 for m in METHODS:metric,arm,z=validate(m);metrics.append(metric);data[m]=(arm,z);render(m,z,OUT/'videos'/f'{m}.mp4') if a.render and not a.no_render else None
 if a.render and not a.no_render:
  import imageio.v2 as imageio
  (OUT/'report').mkdir(parents=True,exist_ok=True)
  readers=[imageio.get_reader(OUT/'videos'/f'{m}.mp4') for m in METHODS];w=imageio.get_writer(OUT/'report/retargeting_methods_grid.mp4',fps=30,codec='libx264',quality=7)
  for frames in zip(*readers):w.append_data(np.concatenate(frames,axis=1))
  w.close();[r.close() for r in readers]
 report(metrics,data);print(json.dumps({'methods':METHODS,'metrics':metrics,'dashboard':str(OUT/'report/index.html')},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
