#!/usr/bin/env python3
"""Publish a scientific-contract decision boundary, never synthetic results."""
from pathlib import Path
import sys,ast
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from tools.run_master_autonomous import *
from tools.master_autonomous_provenance import verified_oracle_contract

TERMINAL='MASTER_SINGLE_VARIABLE_AB_TRUE_SCIENTIFIC_BLOCKER'

def run():
    for p in Path('/proc').iterdir():
        if not p.name.isdigit():continue
        try:args=[a.decode(errors='replace') for a in (p/'cmdline').read_bytes().split(b'\0') if a]
        except (FileNotFoundError,PermissionError,ProcessLookupError):continue
        assert not any(Path(a).name.startswith('run_autonomous_') and a.endswith('.py') for a in args),args
    verified_oracle_contract()
    diag=MASTER/'diagnostics/final_temporal_contract_blocker_v1'
    audit=MASTER/'diagnostics/temporal_gate_semantics_v1'
    d=read(diag/'TRAIN_POSITION_DIAGNOSTIC.json');a=read(audit/'TEMPORAL_ACCEPTANCE_CONTRACT_AUDIT.json')
    assert d['source_position_counts']=={'WRIST':1,'INTERACTION':3}
    assert a['true_stop_condition']==7 and a['no_gate_changed_for_qualification']
    for case in ('WRIST_EP024','WRIST_EP049'):
        assert (RUN/case/'recovered_branch_strict_retry_v1/COMPLETE.json').exists()
        assert (RUN/case/'aggregate_step_semantics_diagnostic_v1/GEOMETRY_COMPLETE.json').exists()
        assert not (RUN/case/'recovered_branch_strict_retry_v1/NUMERIC_PASS.json').exists()
    agap=read(diag/'CERTIFIED_MORPHOLOGY_GAP.json');bgap=read(diag/'B_CERTIFIED_MORPHOLOGY_GAP.json')
    blocker=MASTER/'BLOCKERS/TEMPORAL_ACCEPTANCE_CONTRACT_CONFLICT.md'
    atomic_text(blocker,(audit/'TEMPORAL_ACCEPTANCE_CONTRACT_AUDIT.md').read_text())
    atomic_text(MASTER/'LATEST_BLOCKER.md',blocker.read_text())
    nextpath=MASTER/'NEXT_ACTION_REPORT.md'
    atomic_text(nextpath,'# Scientific decision required before continuation\n\n'+a['decision_required']+'\n\n'+ '\n\n'.join(a['choices'])+'\n\nNeither choice authorizes A/B-specific logic or makes the diagnostic candidates pass: detailed blocked frames remain A24=14,A49=13. Raw targets, event timing,4.5rad/s,130rad/s²,0.15rad scalar steps, joint limits and10μm detailed collision rules remain fixed. After an explicit common contract decision, reuse all persisted witnesses/candidates; do not rerun the completed602-frame forensic. Preserve A00/B00/B24/B49 source passes. Continue position→TRAIN11→6D→loaded Dex3→reference freeze→exact data/action diff→paired rebuild/retrain if required→DEV smoke/freeze→matched DEV35 physics and measured replays.\n')
    cores=[ROOT/'tools'/p for p in ('master_autonomous_common.py','common_constrained_continuation.py','common_fixed_anchor_precision.py','common_fixed_anchor_dense.py','common_wrist_nullspace_search.py','common_hinge_orbit_bounds.py','common_grouped_workspace_bounds.py','common_hard_window_search.py','common_trust_window_search.py')]
    rows=[]
    for p in cores:
        names={n.id for n in ast.walk(ast.parse(p.read_text())) if isinstance(n,ast.Name)}
        forbidden=names & {'representation_mode','episode','case','task_success','physical_outcome','object_pose','method_id'}
        assert not forbidden,(p,forbidden)
        rows.append(dict(file=file_record(p),forbidden_identifiers=[]))
    atomic_json(MASTER/'COMMON_CORE_METHOD_BLIND_AUDIT.json',dict(rows=rows,core_audit_pass=True,execution_qualified=False,dataset_parity='NOT_AUDITED',diagnostic_rule_changes_not_promoted=True))
    parity=OUT/'02_common_execution_qualification/FINAL_COMMON_PIPELINE_PARITY_AUDIT_AUTONOMOUS_V3.md'
    atomic_text(parity,'# Versioned autonomous common pipeline parity audit\n\nRaw WRIST versus INTERACTION target generation remains the only intended representation difference. Protected raw references, registration, source-relative events, models, limits and collision rules retain verified hashes. New numerical cores contain no representation, episode, object-success or outcome input. Failures trigger the same residual/geometry-driven recovery. The separate temporal-semantics diagnostic is explicitly NOT part of accepted execution.\n\nStrict source-position qualification: A1/3,B3/3. No qualified execution freeze, dataset parity, new training parity or DEV35 physical result exists. The unresolved aggregate-step contract requires a scientific decision; neither method received a waiver. See master_autonomous/COMMON_CORE_METHOD_BLIND_AUDIT.json and BLOCKERS/TEMPORAL_ACCEPTANCE_CONTRACT_CONFLICT.md. Earlier audits remain provenance.\n')
    report=OUT/'FINAL_SINGLE_VARIABLE_AB_REBUILD_AND_EVALUATION_REPORT.md'
    old=MASTER/'provenance/FINAL_SINGLE_VARIABLE_AB_REBUILD_AND_EVALUATION_REPORT.md';assert old.exists()
    sections=[
      ('Outcome and true stop condition','True stop condition7: the predeclared aggregate-step maximum and original evaluator implement non-equivalent temporal acceptance. TRAIN evidence demonstrates the difference but does not resolve intended scientific authority. No gate was silently relaxed. This is not a proof of global temporal or physical impossibility. Final DEV35 results are NOT ready.'),
      ('Scientific variable and prior provenance','A=WRIST-trajectory-centric raw spatial target generation; B=INTERACTION-centric raw spatial target generation. All downstream handling is common/method-blind. All earlier physical results remain PRE_FINAL_SINGLE_VARIABLE_REBUILD_DIAGNOSTIC_ONLY and are not mixed with this rebuild. No real G1 hardware commands were sent.'),
      ('Recovered forensic evidence','The completed602-frame dense Cartesian forensic and634 recorded predecessor artifacts were verified and reused. Root cause remains mixed solver-tracking failure and target-embodiment infeasibility. The new analytic hinge-orbit lower bound resolves all four previously uncertified A frames. Bounds certify outside targets only; reachability uses actual valid q witnesses.'),
      ('Raw representation fidelity','Full SMOKE3 A:1772/2066 reachable,294/2066 certified unreachable. B:2036/2066 reachable,30/2066 certified unreachable, all in B00. B49 has no certified-unreachable frames. The older four-trajectory forensic excluded B00 because its old95% gate passed; it did not prove all B targets reachable. No raw targets were overwritten.'),
      ('Registration and event clock','Protected task/workspace registration, source targets, source-relative timestamps and common Dex3 semantic arrays are unchanged. A common preparation prefix shifts global task origin only; it does not dilate or independently retime source events.'),
      ('Natural startup preparation','Authoritative G1 ARM14 natural q0 is exact. Dex3 explicitly uses common OPEN rather than legacy hand preshape; full28-state equality with the legacy file is not claimed. The updated TRAIN11×2 calibration gives0.700s,21 preparation frames plus the source-start endpoint, within a rest-to-rest quintic path family. All22 saved paths and all6 audited candidate source joins pass kinematic checks. The four qualified source trajectories retain those checked joins; later unqualified A24/A49 candidate versions are not promoted by earlier join checks. Final duration freeze remains pending full TRAIN11 source/6D qualification. Physical object contact during preparation is not yet tested.'),
      ('Common morphology realization','Raw and executable q/FK/corrections are stored separately. Certified-unreachable frames use common closest-feasible bounds with0.01mm numerical slack derived from deterministic TRAIN repeatability and the existing10μm resolution floor, not task success. The2mm cap was not substituted as a permissive gate. A exact-raw correction lower mean/p95/max: '+str(agap['raw_position_correction_lower_mm'])+' mm; collision-valid framewise witness upper: '+str(agap['valid_witness_upper_mm'])+' mm. B30-frame bounds: '+str(bgap)+'. These are not DEV35 physical metrics.'),
      ('Executable source-position qualification','Strict source passes A1/3(A00),B3/3(B00,B24,B49). Accepted source trajectories have detailed hard collisions0, unresolved geometry0, hard limits0, finite q, branch violations0 and valid velocity/acceleration/step bounds. A24/A49 remain unqualified. Completed common searches include multiseed propagation, independent and cached witnesses, whole-trajectory feasibility restoration, fixed certified anchors, higher-accuracy sparse solves, dense local continuation, hard-window searches and strict recovery from new branch seeds. No finite local optimizer failure is called a global infeasibility certificate.'),
      ('Temporal contract forensic','Config maximum_step_norm_rad=0.179 and the original solver cap conflict with evaluator semantics: scalar step≤0.15, per-joint qdot≤4.5rad/s, qddot≤130rad/s² and an adaptive branch flag above max(0.18,8×local median). Diagnostic candidates pass Cartesian/per-joint/adaptive-branch checks but have aggregate maxima0.190901rad(A24) and0.271864rad(A49), and14/13 detailed blocked frames. They are NOT qualified. Explicit common acceptance authority is needed; removing the cap alone is not a complete solution.'),
      ('Exact remaining strict failures','See per-frame CSV and temporal audit. Latest strict A24 Cartesian failing frame171; A49 frames166,172,453–457. These latest candidate failures are distinct from historical candidate intervals, all of which remain saved. Reports include exact qdot/qddot/aggregate-step and certified-bound errors.'),
      ('Full6D, loaded Dex3 and reference smoke','NOT RUN because the complete common position prerequisite did not pass. No orientation rescue, loaded14/14 claim, measured-state clipping or structural physical pass is fabricated.'),
      ('Execution freeze','NOT QUALIFIED. Diagnostic hashes are provenance, not a qualified03_common_execution_freeze. No fabricated final execution manifest was issued.'),
      ('Exact old-versus-corrected actions and dataset parity','NOT RUN: no complete qualified executable reference dataset exists. Changed episodes/frames/scalars, timing/normalization/chunks and retraining-required decision remain NOT AUDITED. No corrected dataset generated; unintended dataset confounds are NOT AUDITED, not asserted0.'),
      ('ACT training and policy sanity','No ACT retraining or new checkpoint selection occurred. Existing checkpoints remain unchanged provenance. A common selection contract must precede future training/DEV outcomes. No new policy interface or semantic pass is claimed.'),
      ('DEV35 stages and statistics','No new DEV35 physical rollout: A0executed,B0executed. Stage counts, TSR, paired outcomes, confidence intervals, bootstrap effects and McNemar are unavailable—not0% failure results. DEV35 remains repeatedly inspected development data.'),
      ('Figures, tables and replays','Valid TRAIN-only diagnostics in '+str(diag)+' and '+str(audit)+': per-frameCSV, tableMD/CSV, residual/temporal figures, raw reachability and certified correction distributions inPNG/PDF/SVG. No DEV35 paper figure/table or actual PhysX replay is generated without physical data. No command-only animation substitutes for physics.'),
      ('Fresh-test readiness','NOT READY for frozen untouched-final-test evaluation. The procedure in READY_FOR_UNTOUCHED_FINAL_TEST.md requires completion of execution/data/training/DEV smoke then freeze and fresh collection. No unseen manifest or unseen performance is fabricated.'),
      ('Paper-safe interpretation and next action','Supported conclusions are TRAIN raw morphology feasibility differences and partial common recovery only. No learned-policy superiority, DEV35 success, real-G1 success or autonomous target-domain visual deployment is claimed. Resolve whether0.179rad is independent hard acceptance or internal solver trust radius. Then apply the decision identically to both methods, requalify the complete pipeline and continue from saved artifacts. Do not tune source targets or physical environments from outcomes.')]
    body='# Autonomous single-variable A/B rebuild and evaluation report\n\n'+TERMINAL+'\n\nDiagnostic report ready; final DEV35 results NOT ready.\n\nDiagnostic snapshot SHA256: '+d['diagnostic_snapshot_sha256']+'\n\n'
    for i,(heading,content) in enumerate(sections,1):body+=f'## {i}. {heading}\n\n{content}\n\n'
    atomic_text(report,body)
    ready=OUT/'READY_FOR_UNTOUCHED_FINAL_TEST.md'
    if ready.exists() and not (MASTER/'provenance/READY_FOR_UNTOUCHED_FINAL_TEST.md').exists():atomic_text(MASTER/'provenance/READY_FOR_UNTOUCHED_FINAL_TEST.md',ready.read_text())
    atomic_text(ready,'# Untouched final-test procedure and current readiness\n\nREADY_FOR_UNTOUCHED_FINAL_TEST_EVALUATION = NO\n\nNo complete qualified execution/dataset/checkpoint/scorer freeze exists. DEV35 is development data. Resolve the temporal contract, then qualify complete position/TRAIN11,6D,loaded Dex3 and reference execution. Freeze common execution; compare exact actions/data, rebuild/retrain both only if required using common predeclared checkpoint selection; qualify policies and fixed DEV structural smoke. Freeze all datasets/checkpoints/environments/physics/scorer/cameras/membership. Collect a genuinely fresh FINAL_TEST manifest after freeze, exclude it from all tuning/debugging/selection, and run the identical matched pipeline once. Retain normal failures and rerun only infrastructure-invalid cases. Record actual measured robot and PhysX object states. No fresh set or final result is fabricated.\n')
    _,subs=verified_oracle_contract();atomic_json(MASTER/'REPORT_PUBLICATION_PROVENANCE.json',dict(previous_report=file_record(old),current_report=file_record(report),report_only_substitutions=subs,execution_hash_substitutions=0))
    korean='과학적 중단 조건7: 사전 계약의0.179rad 전체 관절 변화량 상한과 기존 평가 함수의 관절별 속도·가속도/적응형 분기 기준이 일치하지 않습니다. 여러 공통 복구 후 엄격한 위치 통과는 A1/3,B3/3입니다. 별도 진단은 다른 시간 기준에서 위치·속도·가속도를 만족하지만 A24/A49에14/13개 충돌 미통과 프레임이 있어 승격하지 않았습니다. 자연 q0와 공통0.700초 준비 경로22/22 및 저장된 시작 연결6/6은 검증했습니다. 타깃·등록·이벤트·물리 한계·충돌 규칙 및 A/B 공정성을 유지했습니다. 진단 표·그림·최종 보고서를 저장했으며 CLI는 공통 시간 계약의 과학적 선택을 기다립니다.6D·Dex3·학습·DEV35는 미실행입니다.'
    log('TEMPORAL_CONTRACT_SCIENTIFIC_HANDOFF',TERMINAL,[QUAL,audit/'TEMPORAL_ACCEPTANCE_CONTRACT_AUDIT.json',diag/'DIAGNOSTIC_MANIFEST.json'],
        'Non-equivalent temporal rules in predeclared configuration and original evaluator; changing acceptance would materially change qualification',
        'SCIENTIFIC_TEMPORAL_ACCEPTANCE_AMBIGUITY',
        'Completed bounded strict recovery and independent non-promoting diagnostic; preserved all results; no scientific gate or downstream prerequisite bypass.',
        [report,blocker,nextpath,ready,parity],'EXPLICIT_COMMON_TEMPORAL_CONTRACT_DECISION',korean,8)
    atomic_text(OUT/'CURRENT_STATUS.md','# Current authoritative state\n\n'+TERMINAL+'\n\nTrue stop condition7: temporal acceptance contract discrepancy. Strict source position A1/3,B3/3. Natural ARM14 q0 preserved; common0.700s prefix22/22 and6/6 saved candidate joins pass; final TRAIN11/6D freeze pending. Raw certified unreachable A294/2066,B30/2066. Alternative diagnostic candidates are not promoted; detailed blocked frames remain. No6D,Dex3,training orDEV35 physics. See master_autonomous/BLOCKERS/TEMPORAL_ACCEPTANCE_CONTRACT_CONFLICT.md and final report.\n')
    atomic_json(OUT/'CURRENT_STATUS.json',dict(status=TERMINAL,stop_condition=7,source_position_counts=d['source_position_counts'],prepared_pipeline_qualified=False,full_6d='NOT_RUN',loaded_dex3='NOT_RUN',DEV35='NOT_RUN',report=file_record(report)))
    atomic_json(MASTER/'FINAL_RESULT.json',dict(status=TERMINAL,true_stop_condition=7,global_temporal_infeasibility_proven=False,source_position_counts=d['source_position_counts'],raw_certified_counts={'WRIST':294,'INTERACTION':30},DEV35_physical_results=None,report=file_record(report),diagnostics=file_record(diag/'DIAGNOSTIC_MANIFEST.json'),decision=a['decision_required']))
    required=[OUT/'03_common_execution_freeze/COMMON_EXECUTION_FREEZE_MANIFEST.json',*[OUT/'07_paper_artifacts'/p for p in ('TABLE_SINGLE_VARIABLE_AB_DEV35_RESULTS.md','TABLE_SINGLE_VARIABLE_AB_DEV35_RESULTS.csv','FigXX_Single_Variable_AB_DEV35_double.png','FigXX_Single_Variable_AB_DEV35_double.pdf','FigXX_Single_Variable_AB_DEV35_double.svg','FIGURE_RAW_FEASIBILITY_AB.png','FIGURE_STAGE_SUCCESS_AB.png','FIGURE_MATCHED_EPISODE_MATRIX_AB.png')],*[OUT/p for p in ('A_DEV35_FINAL_TOP_35SPLIT.mp4','A_DEV35_FINAL_OVERVIEW_35SPLIT.mp4','B_DEV35_FINAL_TOP_35SPLIT.mp4','B_DEV35_FINAL_OVERVIEW_35SPLIT.mp4')]]
    atomic_json(MASTER/'REQUIRED_FINAL_ARTIFACT_AUDIT.json',dict(status='FINAL_RESULTS_NOT_READY',records=[dict(path=str(p),exists=p.exists(),valid_for_this_rebuild=False,reason='Prerequisite common execution not qualified') for p in required]))
    atomic_json(MASTER/'COMMON_POSITION_BOUNDED_RUN_MANIFEST.json',dict(qualified_full_execution=False,artifacts=[file_record(p) for p in sorted(RUN.rglob('*')) if p.is_file()],drivers=[file_record(p) for p in sorted((ROOT/'tools').glob('run_autonomous_*.py'))]))
    files=[p for p in MASTER.rglob('*') if p.is_file() and p.name!='MASTER_ARTIFACT_MANIFEST.json']+[report,ready,parity,OUT/'CURRENT_STATUS.md',OUT/'CURRENT_STATUS.json']
    atomic_json(MASTER/'MASTER_ARTIFACT_MANIFEST.json',dict(status=TERMINAL,qualified_execution_freeze=False,artifacts=[file_record(p) for p in sorted(set(files))],cores=[file_record(p) for p in cores]))
    manifest=read(MASTER/'MASTER_ARTIFACT_MANIFEST.json');assert all(file_record(Path(r['path']))==r for r in manifest['artifacts']+manifest['cores']);verified_oracle_contract()
    summary='==================================================\nMASTER ALOHA→G1 SINGLE-VARIABLE A/B RESULTS\n==================================================\n\nSTARTUP PREPARATION\nNatural ARM14 q0 preserved:YES\nDex3:common OPEN, not legacy full28 equality\nCommon duration:0.700s provisional;21prefix frames\nPreparation identical A/B:SAME RULE/DURATION;22/22saved paths,6/6saved joins\n\nRAW CARTESIAN FEASIBILITY\nA reachable:1772/2066\nA certified unreachable:294/2066\nA correction lower mean/p95/max mm:'+str(agap['raw_position_correction_lower_mm'])+'\nB reachable:2036/2066\nB certified unreachable:30/2066\nB correction bounds:'+str(bgap)+'\n\nEXECUTABLE POSITION\nA qualified SOURCE:1/3\nB qualified SOURCE:3/3\nHard collision:0in qualified trajectories;other candidates NOT QUALIFIED\nHard limits:0\nAdaptive branch flags:0;remaining aggregate-step and Cartesian failures reported\n\nFULL6D\nA:NOT RUN\nB:NOT RUN\nPosition/orientation residual:NOT AVAILABLE\n\nDEX3\nMapping/sign/readback/runtime limits/measured violations:NOT RUN\n\nDATASET\nA/B action changes:NOT AUDITED\nRegenerated:NO\nUnintended confounds:NOT AUDITED\n\nACT\nRetraining required:NOT AUDITED\nACT-A/B checkpoints:No new selection\n\nDEV35\nA executed:0/35\nB executed:0/35\nA/B Approach/Grasp/Lift/Handoff/Ownership/Transport/Bin/FULL TASK:NOT AVAILABLE\nB-A:NOT AVAILABLE\nMcNemar:NOT AVAILABLE\n\nMAIN DEV35 FIGURE:NOT GENERATED\nDEV35 RESULT TABLE:NOT GENERATED\nA TOP VIDEO:NOT GENERATED\nA OVERVIEW VIDEO:NOT GENERATED\nB TOP VIDEO:NOT GENERATED\nB OVERVIEW VIDEO:NOT GENERATED\nTRAIN DIAGNOSTIC FIGURE:'+str(diag/'FIGURE_TRAIN_POSITION_DIAGNOSTIC.png')+'\nTRAIN DIAGNOSTIC TABLE:'+str(diag/'TABLE_TRAIN_POSITION_DIAGNOSTIC.md')+'\nFINAL REPORT:'+str(report)+'\nCHATGPT UPDATE:'+str(MASTER/'CHATGPT_UPDATE.md')+'\n\n==================================================\n'+TERMINAL
    atomic_text(MASTER/'FINAL_TERMINAL_SUMMARY.txt',summary+'\n');print(summary,flush=True)

if __name__=='__main__':run()
