#!/usr/bin/env python3
"""Create user-approved task semantics and reference-pose review images only."""
from __future__ import annotations
import json,math,sys
from pathlib import Path
import numpy as np
ROOT=Path('/home/jbnu/aloha_g1_dataset');sys.path.insert(0,str(ROOT/'tools'));from task_frame_registration import build
OUT=ROOT/'outputs/task_frame_registration';VIEW=OUT/'approval_views';LAYOUT=ROOT/'isaaclab_magsafe_fixed_scene/scene_layout.json';BUILDER=ROOT/'isaaclab_magsafe_fixed_scene/magsafe_scene_builder.py'
EVENTS=['left_phone_grasp_start','phone_rotation_to_portrait_start','phone_portrait_reached','right_accessory_grasp_start','accessory_detachment_start','accessory_removed','phone_move_to_charger_start','phone_charger_attachment_complete','left_phone_release_complete','left_arm_return_near_home','right_accessory_place_on_table_start','accessory_placed_on_table_complete','task_end']
def dump(p,x):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(x,indent=2)+'\n')
def derived():
 l=json.load(open(LAYOUT));z=l['table']['surface_height'];phone=np.array([sum((l['phone']['bottom_left_xy'][0],l['phone']['bottom_right_xy'][0]))/2,l['phone']['bottom_left_xy'][1],z+l['phone']['size_landscape_xyz'][2]/2]);mount=l['charger']['mount_plate']['size_xyz'][2] if l['charger']['mount_plate']['enabled'] else 0.;root=np.array([*l['charger']['center_xy'],z+mount]);tilt=math.radians(l['charger']['pad_tilt_degrees_up']);r=l['charger']['pad_diameter']/2;n=np.array([0,-math.cos(tilt),math.sin(tilt)]);local=np.array([0,l['charger']['pad_center_y_offset'],l['charger']['total_height']-r*math.cos(tilt)]);center=root+local;face=center+n*(l['charger']['pad_thickness']/2+.0003);return l,phone,root,center,face,n
def definition():
 l,p,cr,pc,pf,n=derived();left=p+np.array([-l['phone']['size_landscape_xyz'][0]/2,0,0])
 d={'schema_version':1,'status':'TASK_SEMANTICS_UPDATED_WAITING_FOR_USER_APPROVAL','simulation_only':True,'trajectory_generated':False,
  'user_approved_task_definition':{'initial':'vertical landscape phone; accessory magnetically attached at phone back-center','intermediate':'left hand rotates/lifts phone to vertical portrait and holds it; right hand removes accessory','final':'vertical portrait phone back attached to tilted charger pad; phone is not laid flat'},
  'poses':{
   'initial_phone_pose':{'semantic_orientation':'VERTICAL_LANDSCAPE','long_axis':'scene left-right','back_surface_normal':'scene +Y','position_scene_m':p.tolist(),'position_status':'VERIFIED_FROM_SCENE_LAYOUT_AND_BUILDER','accessory_relation':'attached at back-center','left_grasp_frame':{'position_scene_m':left.tolist(),'approach_axis_scene':[1,0,0],'closing_axis':'PENDING_APPROVED_LEFT_PHONE_GRASP_START_ALOHA_FK','tolerance':'NOT_DEFINED','source':'USER_APPROVED_ROLE_BUT_POSE_PENDING_VIDEO_ANNOTATION'}},
   'portrait_hold_pose':{'semantic_orientation':'VERTICAL_PORTRAIT','phone_position':'UNKNOWN_DYNAMIC_HELD_POSE','long_axis':'vertical','left_hand':'supports phone at image-left side','right_hand':'accesses back-center accessory','charger_attachment':False,'status':'USER_APPROVED_SEMANTIC_RELATION_POSITION_PENDING_VIDEO_ANNOTATION'},
   'charger_attached_pose':{'semantic_orientation':'VERTICAL_PORTRAIT','phone_center_relation':'aligned with charger pad face center','phone_back_normal_relation':'opposes charger pad outward normal','long_axis':'vertical projected into charger pad tangent plane','position_status':'SEMANTIC_RELATION_ONLY_NO_TRAJECTORY','status':'USER_APPROVED_RELATION_USING_VERIFIED_ASSET_PAD_FRAME'}},
  'hand_roles':{'left':{'object':'phone','functions':['grasp','lift','landscape_to_portrait_rotation','portrait_hold','move_to_charger','attach','release','return_near_home']},'right':{'object':'magsafe_accessory','functions':['approach','grasp','magnetic_detachment','removal','hold_and_transport','place_on_table','release']}},
  'phone_grasp_region':{'deprecated_box_volume':{'status':'UNAPPROVED_HEURISTIC','trajectory_gate_enabled':False,'success_metric_enabled':False},'active_semantic_frame':'initial_phone_pose.left_grasp_frame','final_frame_rule':'compute TCP-to-phone relative transform only after manually approved left_phone_grasp_start frame'},
  'charger_pad_verified_from_asset':{'charger_root_scene_m':cr.tolist(),'pad_center_scene_m':pc.tolist(),'pad_face_center_scene_m':pf.tolist(),'pad_outward_normal_scene':n.tolist(),'pad_radius_m':l['charger']['pad_diameter']/2,'pad_thickness_m':l['charger']['pad_thickness'],'pad_tilt_deg':l['charger']['pad_tilt_degrees_up'],'source':str(BUILDER)+': build_charger_asset','status':'VERIFIED_FROM_ASSET'},
  'timeline_event_order':EVENTS,'right_accessory_phase_order':['ACCESSORY_APPROACH','ACCESSORY_GRASP','ACCESSORY_DETACHMENT','ACCESSORY_HOLD_AND_TRANSPORT','ACCESSORY_TABLE_PLACEMENT','RELEASED'],'accessory_hold_rule':'accessory remains kinematically attached to right palm through accessory_placed_on_table_complete; accessory_removed does not release it','automatic_gripper_phase_policy':'diagnostic only; never automatically approves a semantic event',
  'unknown_values':['portrait-hold phone XYZ','approved left_phone_grasp_start frame','ALOHA TCP-to-phone relative grasp transform','phone left-side tolerance','Dex3 grasp offset','accessory grasp tolerance','accessory removal distance','charger placement tolerance','all angular tolerances','event frame numbers','orientation weights','selected candidate'],
  'user_decisions_still_required':[{'decision':'manually approve left_phone_grasp_start in Episode 49 video','status':'USER_DECISION_REQUIRED'},{'decision':'review derived TCP-to-phone transform after that approval','status':'USER_DECISION_REQUIRED'},{'decision':'approve tolerances and Dex3 offset after visual/real calibration','status':'USER_DECISION_REQUIRED'}],
  'downstream_generation':'BLOCKED'};return d
def plot_pose(path,title,mode,d):
 import matplotlib.pyplot as plt
 from mpl_toolkits.mplot3d.art3d import Poly3DCollection
 l,p,cr,padc,padf,n=derived();fig=plt.figure(figsize=(10,8));ax=fig.add_subplot(111,projection='3d')
 def box(c,size,color):
  c=np.asarray(c);h=np.asarray(size)/2;v=np.array([[i,j,k] for i in (-1,1) for j in (-1,1) for k in (-1,1)])*h+c;faces=[[v[i] for i in f] for f in ((0,1,3,2),(4,5,7,6),(0,1,5,4),(2,3,7,6),(0,2,6,4),(1,3,7,5))];ax.add_collection3d(Poly3DCollection(faces,facecolor=color,alpha=.55,edgecolor=color))
 def arrow(o,v,label,col):ax.quiver(*o,*v,length=.05,normalize=True,color=col);ax.text(*(np.asarray(o)+np.asarray(v)*.055),label,color=col)
 size=np.array(l['phone']['size_landscape_xyz'])
 if mode=='initial':
  c=p;box(c,size,'forestgreen');left=c+[-size[0]/2,0,0];ax.scatter(*left,color='orange',s=70);ax.text(*left,'LEFT semantic grasp frame\nTOLERANCE NOT_DEFINED',color='darkorange');arrow(left,[1,0,0],'approach','orange');arrow(c,[0,1,0],'phone back','cyan')
  r=l['accessory']['main_outer_diameter']/2;t=np.linspace(0,2*np.pi,100);ax.plot(c[0]+r*np.cos(t),np.full_like(t,c[1]+size[1]/2+.001),c[2]+r*np.sin(t),color='black',lw=7);subtitle='INITIAL_PHONE_POSE: VERTICAL_LANDSCAPE | accessory attached back-center'
 elif mode=='hold':
  c=np.zeros(3);box(c,[size[2],size[1],size[0]],'forestgreen');left=c+[-size[2]/2,0,0];ax.scatter(*left,color='orange',s=70);ax.text(*left,'left hand supports phone');arrow(c,[0,1,0],'back-center / right accessory access','cyan');subtitle='PORTRAIT_HOLD semantic orientation only | XYZ UNKNOWN'
 else:
  # Phone long axis is vertical in the pad tangent plane; back normal opposes pad normal.
  long=np.array([0,0,1.])-n*np.dot([0,0,1.],n);long/=np.linalg.norm(long);back=-n;short=np.cross(long,back);R=np.column_stack((long,back,short));c=padf;h=size/2;v=np.array([[i,j,k] for i in (-1,1) for j in (-1,1) for k in (-1,1)])*h;v=v@R.T+c;faces=[[v[i] for i in f] for f in ((0,1,3,2),(4,5,7,6),(0,1,5,4),(2,3,7,6),(0,2,6,4),(1,3,7,5))];ax.add_collection3d(Poly3DCollection(faces,facecolor='forestgreen',alpha=.55));u=np.array([1.,0,0]);vpad=np.cross(n,u);th=np.linspace(0,2*np.pi,100);ring=padc+(l['charger']['pad_diameter']/2)*(np.cos(th)[:,None]*u+np.sin(th)[:,None]*vpad);ax.plot(ring[:,0],ring[:,1],ring[:,2],color='purple',lw=5,label='verified charger pad extent');arrow(padc,n,'charger pad outward normal','purple');arrow(c,back,'phone back outward normal','cyan');subtitle='CHARGER_ATTACHED: VERTICAL_PORTRAIT | center aligned to verified pad face center'
 ax.set_title(title+'\n'+subtitle);ax.text2D(.02,.96,'SEMANTIC REFERENCE ONLY — NO TRAJECTORY',transform=ax.transAxes,color='red',weight='bold');ax.set(xlabel='X',ylabel='Y',zlabel='Z');ax.view_init(20,-55);ax.set_xlim(c[0]-.12,c[0]+.12);ax.set_ylim(c[1]-.12,c[1]+.12);ax.set_zlim(c[2]-.12,c[2]+.12);ax.set_box_aspect((1,1,1));fig.savefig(path,dpi=170,bbox_inches='tight');plt.close(fig)
def main():
 build();d=definition();dump(OUT/'magsafe_task_semantic_definition.json',d);lines=['# MagSafe task semantic definition','','**TASK SEMANTICS UPDATED — NO TRAJECTORY GENERATED — WAITING FOR USER APPROVAL**','',f"- Initial: {d['user_approved_task_definition']['initial']}",f"- Intermediate: {d['user_approved_task_definition']['intermediate']}",f"- Final: {d['user_approved_task_definition']['final']}",'','## Unapproved heuristic','', 'The former orange phone grasp-band volume is `UNAPPROVED_HEURISTIC` and is disabled for trajectory gates and success metrics. Only a left-side semantic grasp frame remains.','','## User decisions required','']+[f"- {x['decision']}" for x in d['user_decisions_still_required']];(OUT/'magsafe_task_semantic_definition.md').write_text('\n'.join(lines)+'\n');VIEW.mkdir(parents=True,exist_ok=True);plot_pose(VIEW/'task_pose_initial_landscape.png','Initial', 'initial',d);plot_pose(VIEW/'task_pose_portrait_hold.png','Intermediate','hold',d);plot_pose(VIEW/'task_pose_charger_attached.png','Final','final',d);print('TASK SEMANTICS UPDATED\nNO TRAJECTORY GENERATED\nWAITING FOR USER APPROVAL');return 0
if __name__=='__main__':raise SystemExit(main())
